#include "sys_init.h"

void initilize_rcc_registers()
{
/*configure bit by bit*/
/*Bad way of doing it but easy to understand*/
  // write_Registers(SYSCTL_RCC_R,SYSCTL_RCC_MOSCDIS);
  SYSCTL_RCC_R =  0x0; // enab;e the main oscillator
  /*Configure OSCRC in RCC to enable internal osciallator*/
  //write_Registers(SYSCTL_RCC_R,SYSCTL_RCC_OSCSRC_INT);
  SYSCTL_RCC_R = (SYSCTL_RCC_R | SYSCTL_RCC_OSCSRC_MAIN); // we want main oscillator as the source
  //change the clock frequenct yo 16.384 Mhz
  SYSCTL_RCC_R = (SYSCTL_RCC_R | SYSCTL_RCC_XTAL_16_3MHZ );
  /*Disable the PLL Bypass*/
  SYSCTL_RCC_R =(SYSCTL_RCC_R | SYSCTL_RCC_BYPASS);
  /*Always say that the PLL is operating normally */
  //SYSCTL_RCC_R = (SYSCTL_RCC_R |0x00);
  //19:17 bit is nit touched and sete to default
  //bit 20 will aslo be take care later
  SYSCTL_RCC_R |= (SYSCTL_RCC_R /*| SYSCTL_RCC_USESYSDIV*/ ) ;//                                USESYSDIV
  //SYSCTL_RCC_R |= (SYSCTL_RCC_R |);// chace of messing thsis up
  //take default to be 0 RCC2 not used as of now // initial devolopment phase

}
/*Override RCC registers*/
void intilize_rcc2_registers()
{
    SYSCTL_RCC2_R = (SYSCTL_RCC2_R | SYSCTL_RCC2_OSCSRC2_MO);
    SYSCTL_RCC2_R = (SYSCTL_RCC2_R | SYSCTL_RCC2_BYPASS2);
    SYSCTL_RCC2_R = (SYSCTL_RCC2_R | SYSCTL_RCC2_SYSDIV2_M );
    SYSCTL_RCC2_R = (SYSCTL_RCC2_R | SYSCTL_RCC2_USERCC2);

}

void sys_init()
{
    system_clkregister_initilize(); 
    systick_initlize();
}

void system_clkregister_initilize()
{
    /*RCC Register initilzation*/
    initilize_rcc_registers();
    //intilize_rcc2_registers();
}

void systick_initlize()
{
   //Initilize ST_Reload Register//
    /*The formula to calculate st_reload register is  given below*/
    /* ST_RELOAD = ( CClk / ticks ) -1  // CClk is the system clock and ticks is number per second. 1 ms is 1000 ticks
     * hence ST_RELOAD = ((16.384*1066)/1000)-1 = 16383
     *
     * )
     * */
    NVIC_ST_RELOAD_R = 0x3FFF;
    NVIC_ST_CURRENT_R = 0x00;
    // pg 138 in datasheet tm4c123
    /* 0 bit is 1 : Systick timer enabled in the multi shot way
     * 1 bit is 1 : An interrupt is generated by NVIC when systick counts to 0
     * 2 bit is 1 : clock source is system clock which is set to 16.383 Mhz
     * 16 bit is1 :systick timer has counted 0 since last time bit was read
     * */
    NVIC_ST_CTRL_R = ((1) | (1<<1) | (1<<2) | (1<<16));


}

void powerdown_sequence()
{
    /*On the powerdown disable the phase locked loop*/
}
