#include "sys_init.h"

#define SET_PORTE_PORTS_OUTPUTS 0x07u

static void  initlize_portA_peripherals(); 
static void initlize_portB_peripherals(); 
static void initilizeportC_peripherals(); 
static void initilizeportD_peripherals(); 
static void initilizeportE_peripherals();
static void initilizeportF_peripherals();



void initilize_rcc_registers()
{
/*configure bit by bit*/
/*Bad way of doing it but easy to understand*/
  // write_Registers(SYSCTL_RCC_R,SYSCTL_RCC_MOSCDIS);
  SYSCTL_RCC_R =  0x0; // enable the main oscillator
  /*Configure OSCRC in RCC to enable internal osciallator*/
  //write_Registers(SYSCTL_RCC_R,SYSCTL_RCC_OSCSRC_INT);
  SYSCTL_RCC_R = (SYSCTL_RCC_R | SYSCTL_RCC_OSCSRC_MAIN); // we want main oscillator as the source
  //change the clock frequenct yo 16.384 Mhz
  SYSCTL_RCC_R = (SYSCTL_RCC_R | SYSCTL_RCC_XTAL_16_3MHZ );
  /*Disable the PLL Bypass*/
  SYSCTL_RCC_R =(SYSCTL_RCC_R | SYSCTL_RCC_BYPASS);
  /*Always say that the PLL is operating normally */
  //SYSCTL_RCC_R = (SYSCTL_RCC_R |0x00);
  //19:17 bit is nit touched and sete to default
  //bit 20 will aslo be take care later
  SYSCTL_RCC_R |= (SYSCTL_RCC_R /*| SYSCTL_RCC_USESYSDIV*/ ) ;//                                USESYSDIV
  //SYSCTL_RCC_R |= (SYSCTL_RCC_R |);// chace of messing thsis up
  //take default to be 0 RCC2 not used as of now // initial devolopment phase

}

/*Override RCC registers*/
void intilize_rcc2_registers()
{
    SYSCTL_RCC2_R = (SYSCTL_RCC2_R | SYSCTL_RCC2_OSCSRC2_MO);
    SYSCTL_RCC2_R = (SYSCTL_RCC2_R | SYSCTL_RCC2_BYPASS2);
    SYSCTL_RCC2_R = (SYSCTL_RCC2_R | SYSCTL_RCC2_SYSDIV2_M );
    SYSCTL_RCC2_R = (SYSCTL_RCC2_R | SYSCTL_RCC2_USERCC2);

}

void unlock_portf()
{
     
}

void initilize_gpio()
{
    //Enable clock to the GPIO  PINS from the RCGC GPIO register
    SYSCTL_RCGCGPIO_R = (SYSCTL_RCGCGPIO_R0 | SYSCTL_RCGCGPIO_R1 | SYSCTL_RCGCGPIO_R2 | SYSCTL_RCGCGPIO_R3 | SYSCTL_RCGCGPIO_R4 | SYSCTL_RCGCGPIO_R5);
    //unlock_portf();
    initlize_portA_peripherals(); 
    initlize_portB_peripherals();
    initilizeportC_peripherals(); 
    initilizeportD_peripherals(); 
    initilizeportE_peripherals();
    initilizeportF_peripherals();
    
    //GPIO_PORTA_DIR_R =
    //Set the GPIO DIR Register
    //Set the port B and Port D register as inputs just for visulixation
    GPIO_PORTB_DIR_R = (0<<4);
    GPIO_PORTD_DIR_R = (0<<7);
    GPIO_PORTE_DIR_R = 0x07u; /*port E is completely configured to be output*/
    /*port A is used for wakeup imnputs */

    //Set the port E register as outputs
    GPIO_PORTE_DIR_R = SET_PORTE_PORTS_OUTPUTS;
    //set the AFSEL register
}   // GPIO_PORTA_AFSEL_R
void initilize_dma()
{

}

void initilize_pwm()
{

}

void initilizea2d()
{

}

void sys_init()
{
    system_clkregister_initilize(); 
    systick_initlize();
    initilize_gpio(); 
    //initlize_spi();
    initilize_dma();
    /*or the enumerations given in i2c.h to activate the required modules
      In this case I am activatiog 0 and 1   */
    //intilize_general_purpose_timer();
    eeprom_driver_init();
    initilize_i2c_structure();
    //initilize_i2c();

}


void system_clkregister_initilize()
{
    /*RCC Register initilzation*/
    initilize_rcc_registers();
    //intilize_rcc2_registers();
}

void systick_initlize()
{
   //Initilize ST_Reload Register//
    /*The formula to calculate st_reload register is  given below*/
    /* ST_RELOAD = ( CClk / ticks ) -1  // CClk is the system clock and ticks is number per second. 1 ms is 1000 ticks
     * hence ST_RELOAD = ((16.384*10^6)/1000)-1 = 16383
     *
     * )
     * */
    NVIC_ST_RELOAD_R = 0x3FFF;
    NVIC_ST_CURRENT_R = 0x00;
    // pg 138 in datasheet tm4c123
    /* 0 bit is 1 : Systick timer enabled in the multi shot way
     * 1 bit is 1 : An interrupt is generated by NVIC when systick counts to 0
     * 2 bit is 1 : clock source is system clock which is set to 16.383 Mhz
     * 16 bit is1 :systick timer has counted 0 since last time bit was read
     * */
    NVIC_ST_CTRL_R = ((1) | (1<<1) | (1<<2) | (1<<16));


}


/*All the GPIO ports initlization sequence */

static void  initlize_portA_peripherals()
{
      /*port A6 and port A7 will be configured as the i2c*/
      /*We are not writing the values for SSI becoause it is a dont care combination */
      //GPIO_PORTA_DIR_R = (gpio_pin_spec[0].gpio_dir << 6)  /*| (gpio_pin_spec[0].gpio_dir <<1)*/; 
      /*Configure AFSEL register */
      GPIO_PORTA_AFSEL_R = ((gpio_pin_spec[6].afsel_setup <<6) | (gpio_pin_spec[6].afsel_setup <<7) | 
                             /*SSI setup */
                            (gpio_pin_spec[32].afsel_setup <<2) | (gpio_pin_spec[32].afsel_setup <<3) | (gpio_pin_spec[32].afsel_setup <<4) | (gpio_pin_spec[32].afsel_setup <<5) |
                             /*set up UART config as well */
                             (gpio_pin_spec[32].afsel_setup) |  (gpio_pin_spec[32].afsel_setup << 1));
                            /*Set the drive strength of the gpio pin */    
                            
      GPIO_PORTA_DR4R_R = ((gpio_pin_spec[6].drive_4mA_out <<6) | (gpio_pin_spec[6].drive_4mA_out <<7) |
                             /*SSI setup */
                            (gpio_pin_spec[32].drive_4mA_out <<2) | (gpio_pin_spec[32].drive_4mA_out <<3) | (gpio_pin_spec[32].drive_4mA_out <<4) | (gpio_pin_spec[32].drive_4mA_out <<5) |
                             (gpio_pin_spec[32].drive_4mA_out)| (gpio_pin_spec[32].drive_4mA_out <<1));   
      /*Set up pull up or pull down configuration */
      GPIO_PORTA_PDR_R = ((gpio_pin_spec[6].pull_down_activate <<6) | (gpio_pin_spec[6].pull_down_activate <<7) | 
                             /*SSI setup */
                            (gpio_pin_spec[32].pull_down_activate <<2) | (gpio_pin_spec[32].pull_down_activate <<3) | (gpio_pin_spec[32].pull_down_activate) 
                            | (gpio_pin_spec[32].pull_down_activate <<4) | (gpio_pin_spec[32].pull_down_activate <<5) | (gpio_pin_spec[32].pull_down_activate <<1));
    /*Activate pull upresestors for i2c */
      GPIO_PORTA_PUR_R = ((gpio_pin_spec[6].pull_up_activate <<6) | (gpio_pin_spec[6].pull_up_activate <<7));
    /*Activate open drain  for i2c*/
      GPIO_PORTA_ODR_R = ((gpio_pin_spec[6].gpio_odr <<7)); 
     /*Set up digital enable register */
      GPIO_PORTA_DEN_R = ((gpio_pin_spec[6].digital_enable <<6) | (gpio_pin_spec[6].digital_enable <<7)  |
                             /*SSI setup */
                            (gpio_pin_spec[32].digital_enable <<2) | (gpio_pin_spec[32].digital_enable <<3) | (gpio_pin_spec[32].digital_enable)
                            | (gpio_pin_spec[32].digital_enable <<4) | (gpio_pin_spec[32].digital_enable <<5) | (gpio_pin_spec[32].digital_enable <<5) | (gpio_pin_spec[32].digital_enable <<1));
    /*GPIOAMSEL set it to 0*/
    /*No need to unlock the gpio*/

}
static void initlize_portB_peripherals()
{
//    Port B6 and B7 are configured as i2c  
    // Configuring AFSEL register

    
    GPIO_PORTB_AFSEL_R = ((gpio_pin_spec[6].afsel_setup <<2) | (gpio_pin_spec[6].afsel_setup << 3));
    GPIO_PORTB_DR4R_R = ((gpio_pin_spec[6].drive_4mA_out <<2) | (gpio_pin_spec[6].drive_4mA_out <<3));
    GPIO_PORTB_PDR_R = ((gpio_pin_spec[6].pull_down_activate <<2) | (gpio_pin_spec[6].pull_down_activate <<3));
    GPIO_PORTB_DEN_R = ((gpio_pin_spec[6].digital_enable <<2) | (gpio_pin_spec[6].digital_enable <<3));
        /*Activate pull upresestors for i2c */
    GPIO_PORTB_PUR_R = ( (gpio_pin_spec[6].gpio_odr <<3));
    /*Activate open drain  for i2c*/
    GPIO_PORTB_ODR_R = ((gpio_pin_spec[6].pull_up_activate <<2) | (gpio_pin_spec[6].pull_up_activate <<3));
}

static void initilizeportC_peripherals()
{
    GPIO_PORTC_AFSEL_R = ((gpio_pin_spec[3].afsel_setup <<4) | (gpio_pin_spec[3].afsel_setup << 5) | (gpio_pin_spec[3].afsel_setup << 6));
    GPIO_PORTC_DR4R_R = ((gpio_pin_spec[3].drive_4mA_out <<4) | (gpio_pin_spec[3].drive_4mA_out <<5) | (gpio_pin_spec[3].drive_4mA_out <<6));
    GPIO_PORTC_PDR_R = ((gpio_pin_spec[3].pull_down_activate <<4) | (gpio_pin_spec[3].pull_down_activate <<5) | (gpio_pin_spec[3].pull_down_activate <<6));
}
static void initilizeportD_peripherals()
{
    /* initilize for i2c */
    GPIO_PORTD_AFSEL_R  = ((gpio_pin_spec[8].afsel_setup <<2) | (gpio_pin_spec[8].afsel_setup <<1));
    GPIO_PORTD_DR4R_R = ((gpio_pin_spec[8].drive_4mA_out <<2) | (gpio_pin_spec[8].drive_4mA_out <<1));
    GPIO_PORTD_PDR_R =  ((gpio_pin_spec[8].pull_down_activate <<2) | (gpio_pin_spec[8].pull_down_activate <<1));
    GPIO_PORTD_DEN_R  =  ((gpio_pin_spec[8].digital_enable <<2) | (gpio_pin_spec[8].digital_enable <<1));
      
}
static void initilizeportE_peripherals(){
    //Port E is for A2D and needs to be configured and i2c have to be configured
}

static void initilizeportF_peripherals()
{
   /*Unlock Port F*/

   /*PORT F Configuration */

    GPIO_PORTF_AFSEL_R  = ((gpio_pin_spec[3].afsel_setup <<1) | (gpio_pin_spec[3].afsel_setup <<2) | (gpio_pin_spec[3].afsel_setup <<3));
    GPIO_PORTF_DR4R_R = ((gpio_pin_spec[3].drive_4mA_out <<1) | (gpio_pin_spec[3].drive_4mA_out <<2) | (gpio_pin_spec[3].drive_4mA_out <<3));
    GPIO_PORTF_PDR_R =  ((gpio_pin_spec[3].pull_down_activate <<1) | (gpio_pin_spec[3].pull_down_activate <<2) | (gpio_pin_spec[3].pull_down_activate <<3));
    GPIO_PORTF_DEN_R  =  ((gpio_pin_spec[3].digital_enable <<1) | (gpio_pin_spec[3].digital_enable <<2) | (gpio_pin_spec[3].digital_enable <<3));
    
}

void powerdown_sequence()
{    /*On the powerdown disable the phase locked loop*/
}
